export const COUNTRIES: { name: string; currency: string; symbol: string }[] = [
  { name: 'Nepal', currency: 'NPR', symbol: 'Rs' },
  { name: 'India', currency: 'INR', symbol: '₹' },
  { name: 'United States', currency: 'USD', symbol: '$' },
  { name: 'United Kingdom', currency: 'GBP', symbol: '£' },
  { name: 'Canada', currency: 'CAD', symbol: 'C$' },
  { name: 'Australia', currency: 'AUD', symbol: 'A$' },
  { name: 'Germany', currency: 'EUR', symbol: '€' },
  { name: 'France', currency: 'EUR', symbol: '€' },
  { name: 'Italy', currency: 'EUR', symbol: '€' },
  { name: 'Spain', currency: 'EUR', symbol: '€' },
  { name: 'Netherlands', currency: 'EUR', symbol: '€' },
  { name: 'Japan', currency: 'JPY', symbol: '¥' },
  { name: 'China', currency: 'CNY', symbol: '¥' },
  { name: 'South Korea', currency: 'KRW', symbol: '₩' },
  { name: 'Brazil', currency: 'BRL', symbol: 'R$' },
  { name: 'Mexico', currency: 'MXN', symbol: 'Mex$' },
  { name: 'South Africa', currency: 'ZAR', symbol: 'R' },
  { name: 'Nigeria', currency: 'NGN', symbol: '₦' },
  { name: 'Kenya', currency: 'KES', symbol: 'KSh' },
  { name: 'Egypt', currency: 'EGP', symbol: 'E£' },
  { name: 'Saudi Arabia', currency: 'SAR', symbol: '﷼' },
  { name: 'UAE', currency: 'AED', symbol: 'د.إ' },
  { name: 'Pakistan', currency: 'PKR', symbol: 'Rs' },
  { name: 'Bangladesh', currency: 'BDT', symbol: '৳' },
  { name: 'Sri Lanka', currency: 'LKR', symbol: 'Rs' },
  { name: 'Thailand', currency: 'THB', symbol: '฿' },
  { name: 'Vietnam', currency: 'VND', symbol: '₫' },
  { name: 'Indonesia', currency: 'IDR', symbol: 'Rp' },
  { name: 'Malaysia', currency: 'MYR', symbol: 'RM' },
  { name: 'Philippines', currency: 'PHP', symbol: '₱' },
  { name: 'Singapore', currency: 'SGD', symbol: 'S$' },
  { name: 'New Zealand', currency: 'NZD', symbol: 'NZ$' },
  { name: 'Turkey', currency: 'TRY', symbol: '₺' },
  { name: 'Russia', currency: 'RUB', symbol: '₽' },
  { name: 'Sweden', currency: 'SEK', symbol: 'kr' },
  { name: 'Switzerland', currency: 'CHF', symbol: 'CHF' },
  { name: 'Poland', currency: 'PLN', symbol: 'zł' },
  { name: 'Argentina', currency: 'ARS', symbol: 'AR$' },
  { name: 'Colombia', currency: 'COP', symbol: 'COL$' },
  { name: 'Chile', currency: 'CLP', symbol: 'CLP$' },
  { name: 'Peru', currency: 'PEN', symbol: 'S/' },
  { name: 'Ethiopia', currency: 'ETB', symbol: 'Br' },
  { name: 'Ghana', currency: 'GHS', symbol: 'GH₵' },
  { name: 'Tanzania', currency: 'TZS', symbol: 'TSh' },
  { name: 'Myanmar', currency: 'MMK', symbol: 'K' },
  { name: 'Cambodia', currency: 'KHR', symbol: '៛' },
].sort((a, b) => a.name.localeCompare(b.name));

export function getCurrencySymbol(region: string): string {
  const country = COUNTRIES.find(c => c.name === region);
  return country?.symbol || '';
}
